### ISSUE TITLE
Consider option to map mkt fields to GA4 expected format

### ISSUE THREAD

**Issue by adatzer** [snowplow/snowplow-gtm-server-side-client#36]
This could aid forwarding Snowplow events to GAv4.
Currently the mappping can become available to GA4 Tag through GTM-SS Transformations, but we could consider adding a configuration option for the Client to do (see "Populate GAv4 Client Properties" config option).

The GAv4 equivalent fields:

![image](https://github.com/snowplow/snowplow-gtm-server-side-client/assets/35838196/60448613-9893-4f75-b6ae-ece3163fb92e)

**Comment by trentusus** [comment]
Full list of GAv4 properties: https://www.simoahava.com/gtm-tips/override-ga4-fields-in-server-side-gtm/

**Comment by adatzer** [comment]
Closing as this mapping being static is probably better managed through GTM-SS transformations cc @trentusus
