### ISSUE TITLE
client unable to claim requests without a header (400 Bad Request)

### ISSUE THREAD

**Issue by nhammad** [snowplow/snowplow-gtm-server-side-client#39]
I have setup GTM server side following this guide: https://aws-solutions-library-samples.github.io/advertising-marketing/using-google-tag-manager-for-server-side-website-analytics-on-aws.html

Now I have two links to access my GTM server: 

Primary Server-Side Container (analytics.example.com)

Preview Server Container (preview-analytics.example.com)

I am using these parameters in the **aws_ecs_task_definition** setup for GTM:

PreviewContainer:

```
  container_definitions    = <<TASK_DEFINITION
  [
  {
    "name": "preview",
    "image": "gcr.io/cloud-tagging-10302018/gtm-cloud-image",
    "environment": [
      {
        "name": "PORT",
        "value": "80"
      },
      {
        "name": "RUN_AS_PREVIEW_SERVER",
        "value": "true"
      },
      {
        "name": "CONTAINER_CONFIG",
        "value": "${var.CONTAINER_CONFIG}"
      }
    ],
```
PrimaryContainer:

```
{
    "name": "primary",
    "image": "gcr.io/cloud-tagging-10302018/gtm-cloud-image",
    "environment": [
      {
        "name": "PORT",
        "value": "80"
      },
      {
        "name": "PREVIEW_SERVER_URL",
        "value": "${var.PREVIEW_SERVER_URL}"
      },
      {
        "name": "CONTAINER_CONFIG",
        "value": "${var.CONTAINER_CONFIG}"
      }
    ]
```

Now I am trying to send data to GTM using Snowbridge, which runs using a docker container on an Ec2 instance. Snowbridge reads data from a Kinesis data stream and forwards it to GTM.

https://docs.snowplow.io/docs/destinations/forwarding-events/snowbridge/configuration/targets/http/google-tag-manager/

config.hcl.tmpl

```
source {
  use "kinesis" {
    stream_name = "${stream_name}"
    region      = "${region}"
    app_name    = "${app_name}"

    role_arn = "${role_arn}"
    read_throttle_delay_ms = 500

    # Maximum concurrent goroutines (lightweight threads) for message processing (default: 50)
    concurrent_writes = 50
  }
}

target {
  use "http" {
    url                        = "https://analytics.xx/com.snowplowanalytics.snowplow/enriched"
    request_timeout_in_seconds = 60
    content_type               = "application/json"

    # this line is optional, in case you want to send events to GTM Preview Mode
    headers                    = "{\"x-gtm-server-preview\": \"AAAAAAAXXXX==\"}"
  }
}

transform {
  use "spEnrichedToJson" {}
}
```
This works as expected and I am able to see incoming data in the preview mode. From my understanding, data is still being sent to the **original mode but it is just being forwarded to the preview mode** when this option is enabled.

When I remove this environment variable for the PreviewContainer to deactivate the Preview mode:
```
 {
        "name": "RUN_AS_PREVIEW_SERVER",
        "value": "true"
 },
```
Snowbridge still successfully sends data (as shown by Cloudwatch logs). If I am not using the Preview Server, that means I would no longer need the "header" in my snowbridge POST requests either. However, as soon as I remove the optional header (i.e., the **x-gtm-server-preview** parameter), I get errors on Snowbridge's Cloudwatch while sending data:

```
level=warning msg="Retrying func (attempts: 2): target.Write: Error sending http requests: 1 error occurred:\n\t* Got response status: 400 Bad Request\n\n"
```
I also checked the logs for the ECS service (Primary Container). As far as I have the header in my POST request, I see statements like these in my logs:

“Snowplow enriched request, claimed...”

but as soon as I remove the header, I no longer see these "claim" statements in the log. 

Is it possible that the snowplow client is not designed to work without a header?

**Comment by adatzer** [comment]
Hi @nhammad ,

To start with:

> Is it possible that the snowplow client is not designed to work without a header?

Do you mean whether the Snowplow Client cannot work for requests without the preview header? If so, this is not the case. 

I haven't tried the guide you shared, so in order to understand what may be at play, can you please confirm on the following about your setup?

1. You mentioned:

    > When I remove this environment variable for the PreviewContainer to deactivate the Preview mode

    Since there is a different container for production(non-preview), why is it needed to change the preview container config? Wouldn't it be possible to just send the events to the prod container?
2. Your preview VS your prod containers are under different URLs (i.e. `analytics.example.com` Vs `preview-analytics.example.com` )? Do you also need to change the `url` besides removing the `header` to send to prod container?
3. Have you published the changes (more specifically the addition of the Client) to your prod container?

**Comment by nhammad** [comment]
1. From my understanding, the events are always being sent to the prod container but when we include the "run_as_preview_server" variable in the previewContainer config, the data is forwarded from the prod container to the preview container.

https://developers.google.com/tag-platform/tag-manager/server-side/manual-setup-guide

But the main problem is the "header" inside the snowbridge target configuration. That's what causes the error 400 upon changes. As soon as I remove the optional header, I get the error.

Note that the header value (x-gtm-server-preview) is not fixed. The token keeps changing. 

* If I use the current valid token, snowbridge successfully sends data to GTM and I can also see it in the Preview Mode
* If I use an old token in the header, snowbridge successfully sends data to GTM (according to the cloudwatch logs) but the data is no longer forwarded to the Preview Mode so it's not visible there. 
* If I use an invalid token for example XXX, which never existed, it again gives a 400 error.

But I don't want to use a header at all.

2. Snowbridge is always sending POST requests to **analytics.example.com**, not to the preview-analytics one. The preview header involves the Preview Mode but the preview link isn't used as such within snowbridge.

3. Yes all changes are up to date. When I check both URLs locally with curl requests, I get an OK for both. 

analytics.example.com/healthz

preview-analytics.example.com/healthz

but when I check locally with the snowplow endpoint, I only get an OK when I use the the preview header. When I don't use the preview header, I don't get any output. Eg:


```
curl --request POST \
  --url https://analytics.example/com.snowplowanalytics.snowplow/enriched \
  --header 'Content-Type: application/json' \
  --header 'x-gtm-server-preview: XXXX' \
  --data '{
  "app_id": "example-website",
  "platform": "web",
  "etl_tstamp": "2021-11-26T00:01:25.292Z",
  "collector_tstamp": "2021-11-20T00:02:05Z",
  "dvce_created_tstamp": "2021-11-20T00:03:57.885Z",
  "event": "unstruct",
  "event_id": "c6ef3124-b53a-4b13-a233-0088f79dcbcb",
  "txn_id": null,
  "name_tracker": "sp1",
  "v_tracker": "js-3.1.6",
  "v_collector": "ssc-2.3.0-stdout$",
  "v_etl": "snowplow-micro-1.1.2-common-2.0.1",
  "user_id": "jon.doe@email.com",
  "user_ipaddress": "92.231.54.234",
  "user_fingerprint": null,
  "domain_userid": "de81d764-990c-4fdc-a37e-adf526909ea6",
  "domain_sessionidx": 3,
  "network_userid": "ecdff4d0-9175-40ac-a8bb-325c49733607",
  "geo_country": "US",
  "geo_region": "CA",
  "geo_city": "San Francisco",
  "geo_zipcode": "94109",
  "geo_latitude": 37.443604,
  "geo_longitude": -122.4124,
  "geo_location": "37.443604,-122.4124",
  "geo_region_name": "San Francisco",
  "ip_isp": "AT&T",
  "ip_organization": "AT&T",
  "ip_domain": "att.com",
  "ip_netspeed": "Cable/DSL",
  "page_url": "https://snowplowanalytics.com/use-cases/",
  "page_title": "Snowplow Analytics",
  "page_referrer": null,
  "page_urlscheme": "https",
  "page_urlhost": "snowplowanalytics.com",
  "page_urlport": 443,
  "page_urlpath": "/use-cases/",
  "page_urlquery": "",
  "page_urlfragment": "",
  "refr_urlscheme": null,
  "refr_urlhost": null,
  "refr_urlport": null,
  "refr_urlpath": null,
  "refr_urlquery": null,
  "refr_urlfragment": null,
  "refr_medium": null,
  "refr_source": null,
  "refr_term": null,
  "mkt_medium": null,
  "mkt_source": null,
  "mkt_term": null,
  "mkt_content": null,
  "mkt_campaign": null,
  "contexts_org_w3_performance_timing_1": [
    {
      "navigationStart": 1415358089861,
      "unloadEventStart": 1415358090270,
      "unloadEventEnd": 1415358090287,
      "redirectStart": 0,
      "redirectEnd": 0,
      "fetchStart": 1415358089870,
      "domainLookupStart": 1415358090102,
      "domainLookupEnd": 1415358090102,
      "connectStart": 1415358090103,
      "connectEnd": 1415358090183,
      "requestStart": 1415358090183,
      "responseStart": 1415358090265,
      "responseEnd": 1415358090265,
      "domLoading": 1415358090270,
      "domInteractive": 1415358090886,
      "domContentLoadedEventStart": 1415358090968,
      "domContentLoadedEventEnd": 1415358091309,
      "domComplete": 0,
      "loadEventStart": 0,
      "loadEventEnd": 0
    }
  ],
  "se_category": null,
  "se_action": null,
  "se_label": null,
  "se_property": null,
  "se_value": null,
  "unstruct_event_com_snowplowanalytics_snowplow_link_click_1": {
    "targetUrl": "http://www.example.com",
    "elementClasses": [
      "foreground"
    ],
    "elementId": "exampleLink"
  },
  "tr_orderid": null,
  "tr_affiliation": null,
  "tr_total": null,
  "tr_tax": null,
  "tr_shipping": null,
  "tr_city": null,
  "tr_state": null,
  "tr_country": null,
  "ti_orderid": null,
  "ti_sku": null,
  "ti_name": null,
  "ti_category": null,
  "ti_price": null,
  "ti_quantity": null,
  "pp_xoffset_min": null,
  "pp_xoffset_max": null,
  "pp_yoffset_min": null,
  "pp_yoffset_max": null,
  "useragent": null,
  "br_name": null,
  "br_family": null,
  "br_version": null,
  "br_type": null,
  "br_renderengine": null,
  "br_lang": null,
  "br_features_pdf": true,
  "br_features_flash": false,
  "br_features_java": null,
  "br_features_director": null,
  "br_features_quicktime": null,
  "br_features_realplayer": null,
  "br_features_windowsmedia": null,
  "br_features_gears": null,
  "br_features_silverlight": null,
  "br_cookies": null,
  "br_colordepth": null,
  "br_viewwidth": null,
  "br_viewheight": null,
  "os_name": null,
  "os_family": null,
  "os_manufacturer": null,
  "os_timezone": null,
  "dvce_type": null,
  "dvce_ismobile": null,
  "dvce_screenwidth": null,
  "dvce_screenheight": null,
  "doc_charset": null,
  "doc_width": null,
  "doc_height": null,
  "tr_currency": null,
  "tr_total_base": null,
  "tr_tax_base": null,
  "tr_shipping_base": null,
  "ti_currency": null,
  "ti_price_base": null,
  "base_currency": null,
  "geo_timezone": null,
  "mkt_clickid": null,
  "mkt_network": null,
  "etl_tags": null,
  "dvce_sent_tstamp": null,
  "refr_domain_userid": null,
  "refr_dvce_tstamp": null,
  "contexts_com_snowplowanalytics_snowplow_ua_parser_context_1": [
    {
      "useragentFamily": "IE",
      "useragentMajor": "7",
      "useragentMinor": "0",
      "useragentPatch": null,
      "useragentVersion": "IE 7.0",
      "osFamily": "Windows XP",
      "osMajor": null,
      "osMinor": null,
      "osPatch": null,
      "osPatchMinor": null,
      "osVersion": "Windows XP",
      "deviceFamily": "Other"
    }
  ],
  "domain_sessionid": "2b15e5c8-d3b1-11e4-b9d6-1681e6b88ec1",
  "derived_tstamp": "2021-11-20T00:03:57.886Z",
  "event_vendor": "com.snowplowanalytics.snowplow",
  "event_name": "link_click",
  "event_format": "jsonschema",
  "event_version": "1-0-0",
  "event_fingerprint": "e3dbfa9cca0412c3d4052863cefb547f",
  "true_tstamp": "2021-11-20T00:03:57.886Z"
}'
```

**Comment by adatzer** [comment]
Thank you for providing more information!
Let's try and isolate the issue:

1. When you are sending requests with `curl` do you notice the exact same behaviour as with Snowbridge? I.e. when valid preview header OK, when no header, 400?
2. If you use the GA4 client (don't forget to publish as well) and send GA4 request (e.g. see below), do you get the same behaviour with and without a preview header?

```
# with header
curl -H 'x-gtm-server-preview: XXXXXXXXX' 'https://analytics.example/g/collect?v=2&en=page_view&tid=G-1234&cid=123.456&dl=https%3A%2F%2Fexample.com%2F'

# without header
curl -H 'https://analytics.example/g/collect?v=2&en=page_view&tid=G-1234&cid=123.456&dl=https%3A%2F%2Fexample.com%2F'
```

**Comment by nhammad** [comment]
1. With the header, I get an OK (200). Without the header, locally, I don't get any response at all but yeah, with Postman, I get a 400.

2. With GA4 client, I get a 200 response with and without the header both

**Comment by adatzer** [comment]
@nhammad unfortunately i cannot replicate this behaviour you describe. What i see is the expected behaviour where the client claims the request with or without the preview header.

So i am not sure what to suggest, but it seems that something is off in your setup. Just some thoughts hoping to help you debug.

You mentioned:

> as soon as I remove the header, I no longer see these "claim" statements in the log.

So, this means that the client hasn't claimed those requests. 

Can you try this?

If "Serve sp.js" is set to true in your **published** container version:

> curl 'https://analytics.example/3.17.0/sp.js'

(This should get you the Snowplow JavaScript tracker) The point is to check whether this request goes through.

The second thing would be to not change your Preview Container ENV var. I mean, when you did:

> When I remove this environment variable for the PreviewContainer to deactivate the Preview mode

Skip this step and leave `RUN_AS_PREVIEW_SERVER` to true in the Preview container. And retry.

**Comment by nhammad** [comment]
I tried this: https://analytics.example/3.17.0/sp.js

but sadly I get a 400 Bad Request. This isn't the actual link I am using ofc. I don't want to publish them here but maybe we could share more details somewhere else?

When you say ""Serve sp.js" is set to true in your published container version", I am assuming you mean here in the client inside GTM:

<img width="1129" alt="Screenshot 2023-11-16 at 18 00 17" src="https://github.com/snowplow/snowplow-gtm-server-side-client/assets/53377055/0cee6d60-6b95-4d71-b51d-3e5d52324dd3">

Yes, RUN_AS_PREVIEW_SERVER is set to true. But the header problem with post requests still exists.

**Comment by adatzer** [comment]
> When you say ""Serve sp.js" is set to true in your published container version", I am assuming you mean here in the client inside GTM:

Yes, exactly.
Let's try one more thing:

In the screenshot it seems you are in a workspace. Is this the one that works with the preview-header?
If so,
can you please hit "Submit":

![image](https://github.com/snowplow/snowplow-gtm-server-side-client/assets/35838196/5ea0f949-2d9f-435c-b18d-90136e809f5e)

and then Publish:

![image](https://github.com/snowplow/snowplow-gtm-server-side-client/assets/35838196/66e04344-7112-4a8e-abd2-70cf83296a35)

Apologies if i am showing you things you may already know, just need to ensure some common ground.

Once this published version is properly up, can you please try the request above (the `sp.js` one) once again?

The reason is that all the above make me suspect that the Client may not be properly published.

**Comment by nhammad** [comment]
ah yes, that was the problem! Might be a good idea to add this in the docs here too (for beginners like me 😅)(https://emojipedia.org/grinning-face-with-sweat)) https://docs.snowplow.io/docs/destinations/forwarding-events/google-tag-manager-server-side/snowplow-client-for-gtm-ss/

With this, I can successfully send post requests with and without the header :D
